name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@master
        uses: actions/checkout@master

      - name: Enable corepack (allow to use yarn)
        run: corepack enable

      - name: actions/setup-node@master
        uses: actions/setup-node@master
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Execute vitest tests
        run: yarn test:unit
